### ISSUE TITLE
Brushes Missing 

### ISSUE THREAD

**Issue by ArmastusChen** [manuelladron/semantic_based_painting#2]
Thanks for the amazing work! 

I were trying to run the code but found there are some texture files related to brushes were missing [here](https://github.com/manuelladron/semantic_based_painting/blob/c83b1a42b1dbbe3e9efbec1cfaf1361fe25fecfe/utils/render_utils.py#L354). Would it be possible if you could upload these files. Thanks!

**Comment by manuelladron** [comment]
Resolved! Thanks for the catch
